"""Convert VisDrone-DET annotations to Ultralytics YOLO format.

Input layout (after download/extract):
    data/raw/VisDrone2019-DET-train/{images,annotations}/
    data/raw/VisDrone2019-DET-val/{images,annotations}/

Output layout (Ultralytics-style):
    data/yolo/VisDrone-DET/
        images/{train,val,test}/*.jpg
        labels/{train,val,test}/*.txt

Split strategy:
    * The official DET-train set -> our `train`.
    * The official DET-val set is divided into our `val` and `test`
      (default 50/50, deterministic by filename hash) so we keep a held-out
      test split without touching the train distribution.

Each output label line is: `class x_center y_center width height` with all
box coords normalized to [0, 1]. Objects in dropped categories (0 ignored,
11 others) and degenerate boxes are skipped. Images with zero kept objects
still get an empty label file (valid YOLO "background" image).
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from collections import Counter
from pathlib import Path

from src.data.config import Paths, load_paths
from src.data.visdrone import (
    CLASS_NAMES,
    NUM_CLASSES,
    parse_annotation_line,
    to_yolo_bbox,
)

IMAGE_EXTS = (".jpg", ".jpeg", ".png", ".bmp")


def _image_size(path: Path) -> tuple[int, int]:
    """Return (width, height) for an image without a heavy CV dependency."""
    from PIL import Image

    with Image.open(path) as img:
        return img.size  # (w, h)


def _assign_val_test(stem: str, test_fraction: float) -> str:
    """Deterministically route a DET-val image to 'val' or 'test'."""
    h = int(hashlib.md5(stem.encode("utf-8")).hexdigest(), 16)
    frac = (h % 10_000) / 10_000.0
    return "test" if frac < test_fraction else "val"


def _convert_one(
    img_path: Path,
    ann_path: Path,
    out_img: Path,
    out_lbl: Path,
    class_counter: Counter,
) -> tuple[int, int]:
    """Convert a single image+annotation pair.

    Returns (kept_boxes, dropped_boxes).
    """
    width, height = _image_size(img_path)

    kept_lines: list[str] = []
    kept = dropped = 0
    if ann_path.exists():
        for raw in ann_path.read_text(encoding="utf-8", errors="ignore").splitlines():
            obj = parse_annotation_line(raw)
            if obj is None:
                continue
            yolo = to_yolo_bbox(obj, width, height)
            if yolo is None:
                dropped += 1
                continue
            cls, xc, yc, w, h = yolo
            class_counter[cls] += 1
            kept_lines.append(f"{cls} {xc:.6f} {yc:.6f} {w:.6f} {h:.6f}")
            kept += 1

    out_img.parent.mkdir(parents=True, exist_ok=True)
    out_lbl.parent.mkdir(parents=True, exist_ok=True)
    # Copy image (cheap relative to retraining; keeps raw untouched).
    if not out_img.exists():
        shutil.copy2(img_path, out_img)
    out_lbl.write_text("\n".join(kept_lines) + ("\n" if kept_lines else ""), encoding="utf-8")
    return kept, dropped


def _iter_pairs(src_root: Path):
    """Yield (image_path, annotation_path) pairs for a VisDrone DET split."""
    images_dir = src_root / "images"
    ann_dir = src_root / "annotations"
    if not images_dir.is_dir():
        raise FileNotFoundError(f"missing images dir: {images_dir}")
    for img_path in sorted(images_dir.iterdir()):
        if img_path.suffix.lower() not in IMAGE_EXTS:
            continue
        yield img_path, ann_dir / f"{img_path.stem}.txt"


def convert_split(
    src_root: Path,
    out_root: Path,
    split_router,
    class_counter: Counter,
) -> dict[str, int]:
    """Convert every image in ``src_root``; ``split_router(stem)`` -> split name."""
    stats: Counter = Counter()
    for img_path, ann_path in _iter_pairs(src_root):
        split = split_router(img_path.stem)
        out_img = out_root / "images" / split / img_path.name
        out_lbl = out_root / "labels" / split / f"{img_path.stem}.txt"
        kept, dropped = _convert_one(img_path, ann_path, out_img, out_lbl, class_counter)
        stats[f"{split}_images"] += 1
        stats[f"{split}_boxes"] += kept
        stats["dropped_boxes"] += dropped
    return dict(stats)


def write_data_yaml(paths: Paths) -> None:
    """(Re)write configs/data.yaml to point at the converted dataset."""
    names_block = "\n".join(f"  {i}: {n}" for i, n in enumerate(CLASS_NAMES))
    content = (
        "# Auto-generated by src/data/convert_visdrone.py — VisDrone-DET (10 classes).\n"
        f"path: {paths.det_yolo_dir.as_posix()}\n"
        "train: images/train\n"
        "val: images/val\n"
        "test: images/test\n\n"
        "names:\n"
        f"{names_block}\n\n"
        f"nc: {NUM_CLASSES}\n"
    )
    paths.data_yaml.write_text(content, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Convert VisDrone-DET -> YOLO format.")
    parser.add_argument("--config", default="configs/paths.yaml")
    parser.add_argument(
        "--test-fraction",
        type=float,
        default=0.5,
        help="fraction of the official DET-val set to reserve as our test split",
    )
    parser.add_argument(
        "--write-data-yaml",
        action="store_true",
        help="rewrite configs/data.yaml to point at the converted dataset",
    )
    args = parser.parse_args(argv)

    paths = load_paths(args.config)
    train_src = paths.raw_dir / "VisDrone2019-DET-train"
    val_src = paths.raw_dir / "VisDrone2019-DET-val"
    out_root = paths.det_yolo_dir

    missing = [p for p in (train_src, val_src) if not p.is_dir()]
    if missing:
        print("Missing source splits (run download_visdrone first):")
        for m in missing:
            print(f"  - {m}")
        return 1

    class_counter: Counter = Counter()

    print(f"Converting train  -> {out_root / 'images' / 'train'}")
    train_stats = convert_split(train_src, out_root, lambda _stem: "train", class_counter)

    print(f"Converting val/test (split {args.test_fraction:.0%} test)")
    valtest_stats = convert_split(
        val_src,
        out_root,
        lambda stem: _assign_val_test(stem, args.test_fraction),
        class_counter,
    )

    if args.write_data_yaml:
        write_data_yaml(paths)
        print(f"Wrote {paths.data_yaml}")

    # --- Summary ---
    merged: Counter = Counter()
    merged.update(train_stats)
    merged.update(valtest_stats)
    print("\n=== Conversion summary ===")
    for split in ("train", "val", "test"):
        print(
            f"  {split:5s}: {merged.get(f'{split}_images', 0):6d} images, "
            f"{merged.get(f'{split}_boxes', 0):8d} boxes"
        )
    print(f"  dropped boxes (ignored/others/degenerate): {merged.get('dropped_boxes', 0)}")
    print("\n  per-class box counts:")
    for cid, name in enumerate(CLASS_NAMES):
        print(f"    {cid} {name:16s}: {class_counter.get(cid, 0):8d}")
    print("\nDone.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
